### ISSUE TITLE
Possible issue with bitshuffle filter on big-endian machines

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/c-blosc#181]
This has been discovered by the PyTables test suite (where a C-Blosc implementing bitshuffle has been vendored into it recently): https://github.com/PyTables/PyTables/issues/583

@kiyo-masui any hints here?

**Comment by kiyo-masui** [comment]
Yeah, I have no idea. I don't think I assumed anything about endianness when I wrote bitshuffle, but I've never had access to a big-endian machine to test on.  I wonder if someone could install the bitshuffle python package on such a machine and run bitshuffle's native test suite. That should test all the bits and pieces independently to narrow down which one breaks.

**Comment by pini-gh** [comment]
How are these tests supposed to be run? Using `python setup.py test` produces nothing:
```
$ python setup.py test
running test
running egg_info
writing requirements to bitshuffle.egg-info/requires.txt
writing bitshuffle.egg-info/PKG-INFO
writing top-level names to bitshuffle.egg-info/top_level.txt
writing dependency_links to bitshuffle.egg-info/dependency_links.txt

#################################
# Compiling with OpenMP support #
#################################

reading manifest file 'bitshuffle.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'setup.cfg'
writing manifest file 'bitshuffle.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-2.7/bitshuffle/ext.so -> bitshuffle
copying build/lib.linux-x86_64-2.7/bitshuffle/h5.so -> bitshuffle
copying build/lib.linux-x86_64-2.7/bitshuffle/plugin/libh5bshuf.so -> bitshuffle/plugin
copying build/lib.linux-x86_64-2.7/bitshuffle/plugin/libh5LZF.so -> bitshuffle/plugin

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by kiyo-masui** [comment]
Install nose and run `nosetests bitshuffle`.

**Comment by pini-gh** [comment]
Here are the result on an s390 Debian porterbox:
```
$ nosetests3 bitshuffle
FF..F...F..........F.......F........F.........F..F...F.FFFFEF
======================================================================
ERROR: test_plugins (bitshuffle.tests.test_h5plugin.TestFilterPlugins)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_h5plugin.py", line 55, in test_plugins
    stdout=PIPE, stderr=STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'h5dump'

======================================================================
FAIL: test_circle (bitshuffle.tests.test_ext.TestBitShuffleCircle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_ext.py", line 517, in test_circle
    == out.view(np.uint8)))
AssertionError: False is not true

======================================================================
FAIL: test_circle_with_compression (bitshuffle.tests.test_ext.TestBitShuffleCircle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_ext.py", line 534, in test_circle_with_compression
    == out.view(np.uint8)))
AssertionError: False is not true

======================================================================
FAIL: test_trans_bit_elem_scal (bitshuffle.tests.test_ext.TestOddLengths)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_ext.py", line 486, in tearDown
    self.assertTrue(np.all(out == ans))
AssertionError: False is not true

======================================================================
FAIL: test_untrans_bit_elem_scal (bitshuffle.tests.test_ext.TestOddLengths)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_ext.py", line 486, in tearDown
    self.assertTrue(np.all(out == ans))
AssertionError: False is not true

======================================================================
FAIL: test_03a_trans_bit_byte (bitshuffle.tests.test_ext.TestProfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_ext.py", line 70, in tearDown
    self.assertTrue(np.all(ans == out.view(np.uint8)))
AssertionError: False is not true

======================================================================
FAIL: test_04e_trans_bit_elem_64 (bitshuffle.tests.test_ext.TestProfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_ext.py", line 70, in tearDown
    self.assertTrue(np.all(ans == out.view(np.uint8)))
AssertionError: False is not true

======================================================================
FAIL: test_06g_untrans_bit_elem_64 (bitshuffle.tests.test_ext.TestProfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_ext.py", line 73, in tearDown
    self.assertTrue(np.all(ans == out.view(np.uint8)))
AssertionError: False is not true

======================================================================
FAIL: test_09a_trans_bit_elem_scal_64 (bitshuffle.tests.test_ext.TestProfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_ext.py", line 70, in tearDown
    self.assertTrue(np.all(ans == out.view(np.uint8)))
AssertionError: False is not true

======================================================================
FAIL: test_09d_untrans_bit_elem_scal_64 (bitshuffle.tests.test_ext.TestProfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_ext.py", line 73, in tearDown
    self.assertTrue(np.all(ans == out.view(np.uint8)))
AssertionError: False is not true

======================================================================
FAIL: test_10b_bitunshuffle_64 (bitshuffle.tests.test_ext.TestProfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_ext.py", line 73, in tearDown
    self.assertTrue(np.all(ans == out.view(np.uint8)))
AssertionError: False is not true

======================================================================
FAIL: test_10d_decompress_64 (bitshuffle.tests.test_ext.TestProfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_ext.py", line 73, in tearDown
    self.assertTrue(np.all(ans == out.view(np.uint8)))
AssertionError: False is not true

======================================================================
FAIL: test_filter (bitshuffle.tests.test_h5filter.TestFilter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_h5filter.py", line 37, in test_filter
    self.assertTrue(np.all(d == data))
AssertionError: False is not true

======================================================================
FAIL: test_with_block_size (bitshuffle.tests.test_h5filter.TestFilter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_h5filter.py", line 59, in test_with_block_size
    self.assertTrue(np.all(d == data))
AssertionError: False is not true

======================================================================
FAIL: test_with_compression (bitshuffle.tests.test_h5filter.TestFilter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_h5filter.py", line 81, in test_with_compression
    self.assertTrue(np.all(d == data))
AssertionError: False is not true

======================================================================
FAIL: test_regression (bitshuffle.tests.test_regression.TestAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pini/debian/bitshuffle/bitshuffle/tests/test_regression.py", line 36, in test_regression
    == g_orig[dset_name][:]))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 61 tests in 0.047s

FAILED (errors=1, failures=15)
```

**Comment by kiyo-masui** [comment]
Okay, lemme look into it a bit.

**Comment by kiyo-masui** [comment]
Indeed the issue is in the following C macro:

    /* Transpose 8x8 bit array packed into a single quadword *x*.
     * *t* is workspace. */
    #define TRANS_BIT_8X8(x, t) {                                               \
            t = (x ^ (x >> 7)) & 0x00AA00AA00AA00AALL;                          \
            x = x ^ t ^ (t << 7);                                               \
            t = (x ^ (x >> 14)) & 0x0000CCCC0000CCCCLL;                         \
            x = x ^ t ^ (t << 14);                                              \
            t = (x ^ (x >> 28)) & 0x00000000F0F0F0F0LL;                         \
            x = x ^ t ^ (t << 28);                                              \
        }

What we want to do is shuffle the bits around is if they were packed in little endian order, independent of architecture. Instead, this macro is architecture dependant.  I copied the macro from here: http://www.hackersdelight.org/hdcodetxt/transpose8.c.txt. That page claims the algorithms work on both LE and BE architecture, but it isn't clear to me what that means.

Someone needs to write a version for a BE machine and swap it in depending on architecture using the preprocessor. Could it be as easy as reversing the order of the three couplets?

**Comment by pini-gh** [comment]
I don't think `TRANS_BIT_8X8` is the culprit. I've tested it on both LE and BE boxes, and it gives the very same int64_t results.

**Comment by kiyo-masui** [comment]
Yes, it gives the same result when interpreting as an int64, but the underlying byte order is different.  We want a function that yields the same underlying byte order, not the same int64 value.

**Comment by pini-gh** [comment]
Oops, sorry, you're right. Coming bask soon with a patch :)

**Comment by pini-gh** [comment]
Here it is.
```
diff --git a/setup.py b/setup.py
index 9fca5b0..0ca4713 100644
--- a/setup.py
+++ b/setup.py
@@ -33,6 +33,9 @@ COMPILE_FLAGS = ['-O3', '-ffast-math', '-march=native', '-std=c99']
 # Cython breaks strict aliasing rules.
 COMPILE_FLAGS += ["-fno-strict-aliasing"]
 
+if sys.byteorder == 'big':
+    COMPILE_FLAGS += ["-DBSHUF_BIGENDIAN"]
+
 MACROS = [
           ('BSHUF_VERSION_MAJOR', VERSION_MAJOR),
           ('BSHUF_VERSION_MINOR', VERSION_MINOR),
diff --git a/src/bitshuffle_core.c b/src/bitshuffle_core.c
index f9d4d4f..5c813da 100644
--- a/src/bitshuffle_core.c
+++ b/src/bitshuffle_core.c
@@ -67,7 +67,15 @@ int bshuf_using_AVX2(void) {
 
 /* Transpose 8x8 bit array packed into a single quadword *x*.
  * *t* is workspace. */
+#ifdef BSHUF_BIGENDIAN
+# include <byteswap.h>
+# define BSWAP_64(x) x = bswap_64(x)
+#else
+# define BSWAP_64(x)
+#endif
+
 #define TRANS_BIT_8X8(x, t) {                                               \
+        BSWAP_64(x);                                                        \
         t = (x ^ (x >> 7)) & 0x00AA00AA00AA00AALL;                          \
         x = x ^ t ^ (t << 7);                                               \
         t = (x ^ (x >> 14)) & 0x0000CCCC0000CCCCLL;                         \
```

Tested successfully on amd64 (LE) and s390x (BE).
```
(sid_amd64-dchroot)pini@barriere:~/debian/bitshuffle$ nosetests bitshuffle
.............................................................
----------------------------------------------------------------------
Ran 61 tests in 2.485s

OK
```
```
(experimental_s390x-dchroot)pini@zelenka:~/debian/bitshuffle$ nosetests3 bitshuffle
.............................................................
----------------------------------------------------------------------
Ran 61 tests in 1.695s

OK
```

**Comment by pini-gh** [comment]
Patch proposal for c-blocs:
```
Index: c-blosc-1.11.1+ds1/blosc/bitshuffle-generic.h
===================================================================
--- c-blosc-1.11.1+ds1.orig/blosc/bitshuffle-generic.h
+++ c-blosc-1.11.1+ds1/blosc/bitshuffle-generic.h
@@ -39,7 +39,14 @@ extern "C" {
 
 /* Transpose 8x8 bit array packed into a single quadword *x*.
  * *t* is workspace. */
+#ifdef BSHUF_BIGENDIAN
+# include <byteswap.h>
+# define BSWAP_64(x) x = bswap_64(x)
+#else
+# define BSWAP_64(x)
+#endif
 #define TRANS_BIT_8X8(x, t) {                                               \
+        BSWAP_64(x)                                                         \
         t = (x ^ (x >> 7)) & 0x00AA00AA00AA00AALL;                          \
         x = x ^ t ^ (t << 7);                                               \
         t = (x ^ (x >> 14)) & 0x0000CCCC0000CCCCLL;                         \
Index: c-blosc-1.11.1+ds1/blosc/CMakeLists.txt
===================================================================
--- c-blosc-1.11.1+ds1.orig/blosc/CMakeLists.txt
+++ c-blosc-1.11.1+ds1/blosc/CMakeLists.txt
@@ -161,6 +161,14 @@ if(COMPILER_SUPPORT_AVX2)
         APPEND PROPERTY COMPILE_DEFINITIONS SHUFFLE_AVX2_ENABLED)
 endif(COMPILER_SUPPORT_AVX2)
 
+INCLUDE(TestBigEndian)
+TEST_BIG_ENDIAN(BIGENDIAN)
+IF(BIGENDIAN)
+    set_property(
+        SOURCE bitshuffle-generic.c
+        APPEND PROPERTY COMPILE_DEFINITIONS BSHUF_BIGENDIAN)
+ENDIF(BIGENDIAN)
+
 # When the option has been selected to compile the test suite,
 # compile an additional version of blosc_shared which exports
 # some normally-hidden symbols (to facilitate unit testing).
```

**Comment by pini-gh** [comment]
I've just tested pytables 3.3.0 built against a patched c-blosc on a s390x box: successful. I confirm this patch solves PyTables/PyTables#583.

**Comment by FrancescAlted** [comment]
Good job guys!  If @kiyo-masui does not have other suggestions, I'll consolidate this patch into C-Blosc and eventually into PyTables.  Thanks!

**Comment by kiyo-masui** [comment]
Two comments: 

1. You detect the system byte order in the python setup.py. I would like to move this to C to make the C source more portable, independent of the python distribution. It says [here](http://stackoverflow.com/questions/4239993/determining-endianness-at-compile-time) that there isn't a good way to do this at compile time. I'm fine with a runtime solution as long as it doesn't affect performance. One way to do this would be to detect the endianness outside the loop, set a function pointer to the appropriate version, then call that function pointer inside the loop. The pointer look up will be optimized away by the compiler.  It isn't clear to be if putting the branch inside the loop would be similarly optimized away.

2. `bswap_64(x)` dominates the operation count which will euker performance on BE machines. Ideally we would have two versions of the macro that each have the same operation count. I guess this one isn't critical, since working, slow code is better than non-working code. Also, rederiving the algorithm is probably non-trivial.

**Comment by FrancescAlted** [comment]
Thanks for your points.  Regarding 1), the solution is implemented at the CMake config file, not setup.py, but I see your point: a runtime solution does not depend on the building framework.  So I'm +1 on a runtime solution (as long as it is trusty, although by reading the answers, it seems a bit hairy).

Regarding 2) I'd vote to start using bswap_64(), but it is not clear to me if this function is portable (e.g. MS Visual Studio?).  After that, we can think in a native macro for BE.

**Comment by kiyo-masui** [comment]
Sorry, I meant the detection is in the setup.py in the bitshuffle patch, not the blosc patch. But yeah, same thing.

I think runtime solutions are straight forward and robust: just casting integer pointers to strings and checking the answers.

I agree that a native BE implementation isn't urgent. I can start thinking about it when I find some time.

**Comment by keszybz** [comment]
Hm, so the patch wants to swap the bytes on big endian, and do a noop on little endian. So why not just do
```
  x = htole64(x); 
```
?

**Comment by FrancescAlted** [comment]
Thanks @keszybz , but from reading the manpage this might be not portable enough.  Perhaps a simpler and more portable solution could be this: https://commandcenter.blogspot.com.es/2012/04/byte-order-fallacy.html

**Comment by ngothan** [comment]
I've tested pytables 3.3.0 built against a patched c-blosc on a ppc64 and confirm this patch solves the bigendian issue in PyTables-3.3.0 on ppc64.

**Comment by kiyo-masui** [comment]
Here is a patch for bitshuffle that I think should work. I think it is portable and it passes the standard test suite, but I don't have access to a BE machine to test that half. If someone could give it a try that would be great.

```
diff --git a/src/bitshuffle_core.c b/src/bitshuffle_core.c
index 3628b9a..29218b4 100644
--- a/src/bitshuffle_core.c
+++ b/src/bitshuffle_core.c
@@ -159,17 +159,31 @@ int64_t bshuf_trans_bit_byte_remainder(const void* in, void* out, const size_t s

     uint64_t x, t;

+    uint64_t e=1;
+    int little_endian = *(uint8_t *) &e == 1;
+
     size_t nbyte = elem_size * size;
     size_t nbyte_bitrow = nbyte / 8;
+    size_t bit_row_skip, bit_row_offset;

     CHECK_MULT_EIGHT(nbyte);
     CHECK_MULT_EIGHT(start_byte);

+    if (little_endian) {
+        bit_row_skip = nbyte_bitrow;
+        bit_row_offset = 0;
+    } else {
+        bit_row_skip = -nbyte_bitrow;
+        bit_row_offset = 8 * nbyte_bitrow;
+    }
+
     for (ii = start_byte / 8; ii < nbyte_bitrow; ii ++) {
         x = in_b[ii];
         TRANS_BIT_8X8(x, t);
         for (kk = 0; kk < 8; kk ++) {
-            out_b[kk * nbyte_bitrow + ii] = x;
+            out_b[bit_row_offset + kk * bit_row_skip + ii] = x;
             x = x >> 8;
         }
     }
```

**Comment by kiyo-masui** [comment]
I updated the patch above just now, because I stupidly used a size_t for a number that could be negative.

**Comment by keszybz** [comment]
So I tried to compile bitshuffle on PPC64 (big endian).

1. gcc does not support `-march=native`, so I had to kick it from COMPILE_FLAGS.

2. I see the following warning:
```
src/bitshuffle_core.c: In function 'bshuf_trans_bit_byte_remainder':
src/bitshuffle_core.c:168:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (ii = start_byte / 8; ii < nbyte_bitrow; ii ++) {
                                  ^
```

3. Without your patch, the tests fail as expected (https://github.com/Blosc/c-blosc/issues/181#issuecomment-258281321)

4. With your patch it dumps core:
```
Using host libthread_db library "/lib64/power8/libthread_db.so.1".
Core was generated by `/usr/bin/python3 /usr/bin/nosetests-3.5 tests/ '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00003fff7bdcf818 in __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:54
54	  return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
[Current thread is 1 (Thread 0x3fff776ef190 (LWP 9266))]
(gdb) bt
#0  0x00003fff7bdcf818 in __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00003fff7bdd1f64 in __GI_abort () at abort.c:89
#2  0x00003fff7be17a28 in __libc_message (do_abort=<optimized out>, fmt=<optimized out>)
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00003fff7be27c34 in malloc_printerr (ar_ptr=<optimized out>, ptr=0x3fff700008c0, 
    str=0x3fff7bf2adc0 "double free or corruption (!prev)", action=<optimized out>) at malloc.c:5004
#4  _int_free (have_lock=0, p=<optimized out>, av=<optimized out>) at malloc.c:3865
#5  __GI___libc_free (mem=<optimized out>) at malloc.c:2966
#6  0x00003fff7a384f20 in bshuf_trans_bit_elem_scal (in=<optimized out>, out=0x1000cce7030, size=8192, elem_size=1)
    at src/bitshuffle_core.c:248
#7  0x00003fff7a3855a0 in bshuf_trans_bit_elem (in=<optimized out>, out=<optimized out>, size=<optimized out>, 
    elem_size=<optimized out>) at src/bitshuffle_core.c:1098
#8  0x00003fff7a385668 in bshuf_bitshuffle_block (C_ptr=0x3fffdc7b66a8, size=8192, elem_size=1)
    at src/bitshuffle_core.c:1198
#9  0x00003fff7a384784 in bshuf_blocked_wrap_fun._omp_fn.0 () at src/bitshuffle_core.c:1150
#10 0x00003fff7a320a34 in gomp_thread_start (xdata=<optimized out>) at ../../../libgomp/team.c:119
#11 0x00003fff7c0fbd64 in start_thread (arg=0x3fff776ef190) at pthread_create.c:335
#12 0x00003fff7beba2a0 in .__clone () at ../sysdeps/unix/sysv/linux/powerpc/powerpc64/clone.S:96
```

Running under valgrind:
```
$ valgrind /usr/bin/python3 -m nose tests/
==9290== Memcheck, a memory error detector
==9290== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==9290== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==9290== Command: /usr/bin/python3 -m nose tests/
==9290== 
==9290== Thread 3:
==9290== Invalid write of size 1
==9290==    at 0x90F4BF0: bshuf_trans_bit_byte_remainder (bitshuffle_core.c:185)
==9290==    by 0x90F4C93: bshuf_trans_bit_byte_scal (bitshuffle_core.c:197)
==9290==    by 0x90F559F: bshuf_trans_bit_elem (bitshuffle_core.c:1098)
==9290==    by 0x90F5667: bshuf_bitshuffle_block (bitshuffle_core.c:1198)
==9290==    by 0x90F4783: bshuf_blocked_wrap_fun._omp_fn.0 (bitshuffle_core.c:1150)
==9290==    by 0x9150A33: gomp_thread_start (team.c:119)
==9290==    by 0x4CBBD63: start_thread (pthread_create.c:335)
==9290==    by 0x4FAA29F: clone (clone.S:96)
==9290==  Address 0x9256580 is 0 bytes after a block of size 8,192 alloc'd
==9290==    at 0x48962D4: malloc (vg_replace_malloc.c:299)
==9290==    by 0x90F4EAF: bshuf_trans_bit_elem_scal (bitshuffle_core.c:239)
==9290==    by 0x90F559F: bshuf_trans_bit_elem (bitshuffle_core.c:1098)
==9290==    by 0x90F5667: bshuf_bitshuffle_block (bitshuffle_core.c:1198)
==9290==    by 0x90F4783: bshuf_blocked_wrap_fun._omp_fn.0 (bitshuffle_core.c:1150)
==9290==    by 0x9150A33: gomp_thread_start (team.c:119)
==9290==    by 0x4CBBD63: start_thread (pthread_create.c:335)
==9290==    by 0x4FAA29F: clone (clone.S:96)
==9290== 
--9290-- VALGRIND INTERNAL ERROR: Valgrind received a signal 11 (SIGSEGV) - exiting
--9290-- si_code=1;  Faulting address: 0xC0FB92498991B2D0;  sp: 0x80f2afb50

valgrind: the 'impossible' happened:
   Killed by fatal signal
```

**Comment by kiyo-masui** [comment]
Well that failed spectacularly!

There is an 8 in there that should be a 7. I'll send another patch tomorrow.

**Comment by kiyo-masui** [comment]
Okay, in addition to screwing up my pointers in the last patch, I had also forgotten half the job: fixing decompression as well. New patch:

```
diff --git a/src/bitshuffle_core.c b/src/bitshuffle_core.c
index 3628b9a..236e35b 100644
--- a/src/bitshuffle_core.c
+++ b/src/bitshuffle_core.c
@@ -153,23 +153,36 @@ int64_t bshuf_trans_byte_elem_scal(const void* in, void* out,
 const size_t size,
 int64_t bshuf_trans_bit_byte_remainder(const void* in, void* out, const size_t siz
e,
          const size_t elem_size, const size_t start_byte) {

-    int ii, kk;
     const uint64_t* in_b = (const uint64_t*) in;
     uint8_t* out_b = (uint8_t*) out;

     uint64_t x, t;

+    size_t ii, kk;
     size_t nbyte = elem_size * size;
     size_t nbyte_bitrow = nbyte / 8;
+    size_t bit_row_offset;
+    int64_t bit_row_skip;
+
+    uint64_t e=1;
+    int little_endian = *(uint8_t *) &e == 1;

     CHECK_MULT_EIGHT(nbyte);
     CHECK_MULT_EIGHT(start_byte);

+    if (little_endian) {
+        bit_row_skip = nbyte_bitrow;
+        bit_row_offset = 0;
+    } else {
+        bit_row_skip = -nbyte_bitrow;
+        bit_row_offset = 7 * nbyte_bitrow;
+    }
+
     for (ii = start_byte / 8; ii < nbyte_bitrow; ii ++) {
         x = in_b[ii];
         TRANS_BIT_8X8(x, t);
         for (kk = 0; kk < 8; kk ++) {
-            out_b[kk * nbyte_bitrow + ii] = x;
+            out_b[bit_row_offset + kk * bit_row_skip + ii] = x;
             x = x >> 8;
         }
     }
@@ -270,18 +283,31 @@ int64_t bshuf_trans_byte_bitrow_scal(const void* in, void* out, const size_t siz
 int64_t bshuf_shuffle_bit_eightelem_scal(const void* in, void* out, \
         const size_t size, const size_t elem_size) {

-    size_t ii, jj, kk;
     const char *in_b;
     char *out_b;
     uint64_t x, t;
-    size_t nbyte;
+    size_t ii, jj, kk;
+    size_t nbyte, out_index;
+
+    uint64_t e=1;
+    int little_endian = *(uint8_t *) &e == 1;

+    size_t elem_offset;
+    uint64_t elem_skip;

     CHECK_MULT_EIGHT(size);

     in_b = (const char*) in;
     out_b = (char*) out;

+    if (little_endian) {
+        elem_skip = elem_size;
+        elem_offset = 0;
+    } else {
+        elem_skip = -elem_size;
+        elem_offset = 7 * elem_size;
+    }
+
     nbyte = elem_size * size;

     for (jj = 0; jj < 8 * elem_size; jj += 8) {
@@ -289,7 +315,8 @@ int64_t bshuf_shuffle_bit_eightelem_scal(const void* in, void* out, \
             x = *((uint64_t*) &in_b[ii + jj]);
             TRANS_BIT_8X8(x, t);
             for (kk = 0; kk < 8; kk++) {
-                *((uint8_t*) &out_b[ii + jj / 8 + kk * elem_size]) = x;
+                out_index = ii + jj / 8 + elem_offset + kk * elem_skip;
+                *((uint8_t*) &out_b[out_index]) = x;
                 x = x >> 8;
             }
         }
```

**Comment by keszybz** [comment]
Can you post your patch as a PR or at least a text file somewhere? It's corrupted in the github comment.

**Comment by kiyo-masui** [comment]
kiyo-masui/bitshuffle#56

**Comment by jakirkham** [comment]
Fixed in PR ( https://github.com/kiyo-masui/bitshuffle/pull/58 ), which appears to be in 0.3.0+. What do we need to do to get that fix in Blosc?

**Comment by FrancescAlted** [comment]
Nice that you fixed that.  To test with Blosc, the only necessary thing is to replace these files:

```
blosc/bitshuffle-avx2.c		blosc/bitshuffle-generic.c	blosc/bitshuffle-sse2.c
blosc/bitshuffle-avx2.h		blosc/bitshuffle-generic.h	blosc/bitshuffle-sse2.h
```

with the newer ones.

You are welcome to try this out and send a PR.

**Comment by FrancescAlted** [comment]
There is a PR for fixing this in #189. @ngothan or @keszybz could you have this a go on a big endian machine and tell me how it goes?
