### ISSUE TITLE
Segfaults in tests on armhf architecture

### ISSUE THREAD

**Issue by estan** [Blosc/c-blosc#223]
@FrancescAlted It seems I spoke too soon about the Ubuntu package, it has been held back in bionic-proposed because of some segfaults in the tests during the package build on the armhf architecture:

https://launchpadlibrarian.net/360527843/buildlog_ubuntu-bionic-armhf.c-blosc_1.14.0+ds1-1_BUILDING.txt.gz

:( At the moment I don't have more information, I'll see if I can somehow reproduce the issue when I'm at work, but it's a little awkward since I don't have any armhf hardware. Do you?

**Comment by estan** [comment]
What's strange is that the Debian armhf build of the very same package succeeded fine though:

https://buildd.debian.org/status/fetch.php?pkg=c-blosc&arch=armhf&ver=1.14.0%2Bds1-1&stamp=1520877290&raw=0

Guess it must be something specific to Ubuntu that triggers it.

**Comment by FrancescAlted** [comment]
Hmm, yes, it is interesting to see Ubuntu and Debian on armhf having different outcomes.  There are different possibilities to reproduce an armhf environment.  Here are some links:

https://gist.github.com/Liryna/10710751
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Virtual_ARM_Linux_environment

I'll try to see if I can reproduce that by the end of the week, but if you want to try that in parallel, great!

**Comment by estan** [comment]
@FrancescAlted Here's some input from Adam Conrad in #ubuntu-release IRC channel on Freenode. He's the one who did the upload to bionic-proposed:

```
08:12 < infinity> estan: If Debian's works and ours doesn't, there's a fair chance the issues are alignment-related.
08:13 < infinity> estan: Debian runs on ARMv7 hardware with alignment fixups at runtime.  We run on ARMv8 hardware that falls over on unaligned access with ARMv7
                  code.
08:14 < infinity> estan: 9 times out of 10, that'll be a SIGBUS, not a SIGSEGV, but when you do it just wrong, segfaults occur, so my bet's on that.
08:16 < tjaalton> is LP selective with it's debian mirror? some packages seem to not have "been picked up by LP yet", while newer ones have
08:16 < infinity> estan: Upshot of caring about unaligned access is that it'll be a (very minor) performance increase on even x86 for upstream to fix it. :P
```

**Comment by FrancescAlted** [comment]
Yep, alignment issues are a possible cause indeed.  However, it seems to me that unaligned access is currently [disabled in ARM architectures](https://github.com/Blosc/c-blosc/blob/master/blosc/blosc-common.h#L64), so perhaps the problem is that not enough `BLOSC_STRICT_ALIGN` checks have been made.  Hmm, I think I'd need to setup an armhf environment and test by myself.

BTW, I don't find the #ubuntu-release channel in https://wiki.ubuntu.com/IRC/ChannelList

**Comment by estan** [comment]
@FrancescAlted Alright, yes getting blosc up and running in a debugger on armhf is probably the only way to find out for sure.

Hm not sure why they don't advertise #ubuntu-release in that list. Perhaps they don't want too many people walking in there asking for package upgrades et.c. But the channel exists :) I know it's mentioned in the instructions for SRU (stable release updates): https://wiki.ubuntu.com/StableReleaseUpdates#Publishing

**Comment by estan** [comment]
Some of the comments on this issue on a completely different project, but about essentially the same thing, suggests that it may be hard to provoke this without real ARM hardware :( https://github.com/mapbox/protozero/issues/33

At least some of the comments suggest that e.g. QEMU won't fault in the same way as the real thing. Not sure if it applied to current versions of QEMU.

I didn't have too much time to look at this today, but will try getting an armhf VM running when I get the time.

**Comment by FrancescAlted** [comment]
Yep, I have been trying via Qemu on a Ubuntu 16.04, but I cannot make this fail:

```
parallels@parallels-vm:~/arm/c-blosc/bench$ arm-linux-gnueabihf-gcc -static -O3 bench.c -I../blosc -o bench ../blosc/blosc.c ../blosc/fastcopy.c ../blosc/shuffle.c ../blosc/bitshuffle-generic.c ../blosc/shuffle-generic.c ../blosc/blosclz.c -lpthread 
../blosc/shuffle.c:288:4: warning: #warning Hardware-acceleration detection not implemented for the target architecture. Only the generic shuffle/unshuffle routines will be available. [-Wcpp]
parallels@parallels-vm:~/arm/c-blosc/bench$ file bench
bench: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=baf4bc2bbd96e1a10d57b1c2636c80ced4e582b0, not stripped
parallels@parallels-vm:~/arm/c-blosc/bench$ ./bench blosclz
Blosc version: 1.14.1.dev ($Date:: 2018-02-23 #$)
List of supported compressors in this build: blosclz
Supported compression libraries:
  BloscLZ: 1.1.0
  LZ4: unknown
  Snappy: unknown
  Zlib: unknown
  Zstd: unknown
Using compressor: blosclz
Using shuffle type: shuffle
Running suite: single
--> 4, 2097152, 8, 19, blosclz, shuffle
********************** Run info ******************************
Blosc version: 1.14.1.dev ($Date:: 2018-02-23 #$)
Using synthetic data with 19 significant bits (out of 32)
Dataset size: 2097152 bytes	Type size: 8 bytes
Working set: 256.0 MB		Number of threads: 4
********************** Running benchmarks *********************
memcpy(write):		  847.4 us, 2360.1 MB/s
memcpy(read):		  711.9 us, 2809.6 MB/s
Compression level: 0
comp(write):	  962.7 us, 2077.5 MB/s	  Final bytes: 2097168  Ratio: 1.00
decomp(read):	  973.3 us, 2054.9 MB/s	  OK
Compression level: 1
comp(write):	 11725.4 us, 170.6 MB/s	  Final bytes: 539248  Ratio: 3.89
decomp(read):	 5033.4 us, 397.3 MB/s	  OK
Compression level: 2
comp(write):	 11354.8 us, 176.1 MB/s	  Final bytes: 137584  Ratio: 15.24
decomp(read):	 12936.8 us, 154.6 MB/s	  OK
Compression level: 3
comp(write):	 10829.6 us, 184.7 MB/s	  Final bytes: 101272  Ratio: 20.71
decomp(read):	 12733.9 us, 157.1 MB/s	  OK
Compression level: 4
comp(write):	 10506.3 us, 190.4 MB/s	  Final bytes: 101272  Ratio: 20.71
decomp(read):	 12549.1 us, 159.4 MB/s	  OK
Compression level: 5
comp(write):	 10219.6 us, 195.7 MB/s	  Final bytes: 85248  Ratio: 24.60
decomp(read):	 10883.6 us, 183.8 MB/s	  OK
Compression level: 6
comp(write):	 10273.6 us, 194.7 MB/s	  Final bytes: 85248  Ratio: 24.60
decomp(read):	 10832.0 us, 184.6 MB/s	  OK
Compression level: 7
comp(write):	 10121.7 us, 197.6 MB/s	  Final bytes: 85248  Ratio: 24.60
decomp(read):	 10882.1 us, 183.8 MB/s	  OK
Compression level: 8
comp(write):	 10325.0 us, 193.7 MB/s	  Final bytes: 85248  Ratio: 24.60
decomp(read):	 11144.3 us, 179.5 MB/s	  OK
Compression level: 9
comp(write):	 10136.5 us, 197.3 MB/s	  Final bytes: 85248  Ratio: 24.60
decomp(read):	 10787.3 us, 185.4 MB/s	  OK

Round-trip compr/decompr on 7.5 GB
Elapsed time:	   75.6 s, 223.5 MB/s
```

So probably we would need access to a native ARM platform, yes.

**Comment by estan** [comment]
@FrancescAlted I dug around a little in QEMU code, and I think you need a newer QEMU than the one in Ubuntu 16.04 to get support for ARMv8 unaligned access exceptions. I'm trying to build a QEMU from Git now.

**Comment by FrancescAlted** [comment]
So, I went ahead and got a bare metal ARM server (C1 in https://www.scaleway.com/), but no luck:

```
root@scw-e94a6c:~/c-blosc/build# file bench/bench 
bench/bench: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=2bba5a52ed4a81879046a49bb165905fa174d5db, not stripped

root@scw-e94a6c:~/c-blosc/build# bench/bench blosclz
Blosc version: 1.14.1.dev ($Date:: 2018-02-23 #$)
List of supported compressors in this build: blosclz,lz4,lz4hc,snappy,zlib,zstd
Supported compression libraries:
  BloscLZ: 1.1.0
  LZ4: 1.8.1
  Snappy: 1.1.1
  Zlib: 1.2.8
  Zstd: 1.3.3
Using compressor: blosclz
Using shuffle type: shuffle
Running suite: single
--> 4, 2097152, 8, 19, blosclz, shuffle
********************** Run info ******************************
Blosc version: 1.14.1.dev ($Date:: 2018-02-23 #$)
Using synthetic data with 19 significant bits (out of 32)
Dataset size: 2097152 bytes	Type size: 8 bytes
Working set: 256.0 MB		Number of threads: 4
********************** Running benchmarks *********************
memcpy(write):		 4071.0 us, 491.3 MB/s
memcpy(read):		 3677.5 us, 543.8 MB/s
Compression level: 0
comp(write):	 2193.2 us, 911.9 MB/s	  Final bytes: 2097168  Ratio: 1.00
decomp(read):	 2003.7 us, 998.1 MB/s	  OK
Compression level: 1
comp(write):	 8934.7 us, 223.8 MB/s	  Final bytes: 539248  Ratio: 3.89
decomp(read):	 6538.0 us, 305.9 MB/s	  OK
Compression level: 2
comp(write):	 10770.2 us, 185.7 MB/s	  Final bytes: 137584  Ratio: 15.24
decomp(read):	 7711.9 us, 259.3 MB/s	  OK
Compression level: 3
comp(write):	 12630.2 us, 158.4 MB/s	  Final bytes: 101272  Ratio: 20.71
decomp(read):	 8614.2 us, 232.2 MB/s	  OK
Compression level: 4
comp(write):	 12619.3 us, 158.5 MB/s	  Final bytes: 101272  Ratio: 20.71
decomp(read):	 8608.2 us, 232.3 MB/s	  OK
Compression level: 5
comp(write):	 12380.9 us, 161.5 MB/s	  Final bytes: 85248  Ratio: 24.60
decomp(read):	 9034.0 us, 221.4 MB/s	  OK
Compression level: 6
comp(write):	 12404.8 us, 161.2 MB/s	  Final bytes: 85248  Ratio: 24.60
decomp(read):	 8556.7 us, 233.7 MB/s	  OK
Compression level: 7
comp(write):	 12406.0 us, 161.2 MB/s	  Final bytes: 85248  Ratio: 24.60
decomp(read):	 8547.6 us, 234.0 MB/s	  OK
Compression level: 8
comp(write):	 12393.1 us, 161.4 MB/s	  Final bytes: 85248  Ratio: 24.60
decomp(read):	 8599.0 us, 232.6 MB/s	  OK
Compression level: 9
comp(write):	 12629.0 us, 158.4 MB/s	  Final bytes: 85248  Ratio: 24.60
decomp(read):	 8541.6 us, 234.1 MB/s	  OK

Round-trip compr/decompr on 7.5 GB
Elapsed time:	   74.6 s, 226.5 MB/s
```

The hardware is this:

```
root@scw-e94a6c:~/c-blosc/build# cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 2 (v7l)
BogoMIPS	: 50.00
Features	: half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae 
CPU implementer	: 0x56
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0x584
CPU revision	: 2

processor	: 1
model name	: ARMv7 Processor rev 2 (v7l)
BogoMIPS	: 50.00
Features	: half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae 
CPU implementer	: 0x56
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0x584
CPU revision	: 2

processor	: 2
model name	: ARMv7 Processor rev 2 (v7l)
BogoMIPS	: 50.00
Features	: half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae 
CPU implementer	: 0x56
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0x584
CPU revision	: 2

processor	: 3
model name	: ARMv7 Processor rev 2 (v7l)
BogoMIPS	: 50.00
Features	: half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae 
CPU implementer	: 0x56
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0x584
CPU revision	: 2

Hardware	: Marvell Armada 370/XP (Device Tree)
Revision	: 0000
Serial		: 0000000000000000
```

Not sure if that's the one that crashes in Ubuntu armhf.

**Comment by estan** [comment]
@FrancescAlted Ah no, I believe that the problem is specific to ARMv8 (which Ubuntu uses on its package building infrastructure). The alignment requirements there are a little different than those on ARMv7 if I understand correctly. Debian uses ARMv7 on its package building infrastructure. That's probably why the Debian build succeeded but the Ubuntu one failed.

**Comment by mwhudson** [comment]
I saw the conversation in #ubuntu-release and managed to reproduced this on an Ubuntu porter box. The crash is this line: https://github.com/Blosc/c-blosc/blob/master/blosc/fastcopy.c#L452:

```
452	      *(uint64_t *) out = *(uint64_t *) from;
(gdb) l
447	    case 32:
448	      return copy_32_bytes(out, from);
449	    case 16:
450	      return copy_16_bytes(out, from);
451	    case 8:
452	      *(uint64_t *) out = *(uint64_t *) from;
453	      out += 8;
454	      return out;
455	    default: {
456	    }
(gdb) bt
#0  fastcopy (out=out@entry=0xe3a04840 "", 
    from=from@entry=0xf6beb2f3 "\222\202\262\242\322\302\362\342\307'\v\223\203\263\243\323\303\363\343\023\003\063#B\273\a\224\204\264\244\324\304\364\344\306\347\v\225\205\265\245\325\305\365\345\025\005\065%B{\a\226\206\266\246\326\306\366\346\307'\v\227\207\267\247\327\307\367\347\027\a7'B\273\a\231\211\271\251\331\311\371\351\306\347\v\230\210\270\250\330\310\370\350\030\b8(C{\a\233\213\273\253\333\313\373\353\307'\v\232\212\272\252\332\312\372\352\032\n:*C\273\a\235\215\275\255\335\315\375\355\306\347\v\234\214\274\254\334\314\374\354\034\f<,C{\a\237\217\277\257\337\317\377\357\307'\v\236\216\276\256\336\316\376\356\036\016>.C\273\a\202\222\242\262\302\322\342\362\310\347\v\203\223\243\263\303\323\343"..., len=8) at ./blosc/fastcopy.c:452
#1  0xf777b766 in blosclz_decompress (input=input@entry=0xf6beaad8, length=length@entry=7861, output=output@entry=0xe3a04020, 
    maxout=maxout@entry=32768) at ./blosc/blosclz.c:515
#2  0xf777934a in blosc_d (context=<optimized out>, blocksize=262144, leftoverblock=leftoverblock@entry=0, src=0xf6beaad8 "?", 
    dest=dest@entry=0xf6ddf020 "", tmp=tmp@entry=0xe39fc020 "", tmp2=tmp2@entry=0xe3a3c020 "") at ./blosc/blosc.c:725
#3  0xf7779eba in t_blosc (ctxt=0x41a500) at ./blosc/blosc.c:1749
#4  0xf7660614 in start_thread (arg=0xb84515f6) at pthread_create.c:463
```

I just deleted the whole "case 8" block and the tests now pass so it seems this is the only problematic line.

**Comment by estan** [comment]
@mwhudson: Excellent, many thanks. @FrancescAlted: Should be an easy fix right?

(Not sure, but I think what made this so hard to reproduce is that Ubuntu builds armhf packages in an armhf chroot on ARMv8 hw using a syscall-emulating QEMU that lies about the CPU.)

**Comment by FrancescAlted** [comment]
@mwhudson Good catch!  Yes, I can see the flaw.  I'll fix it and try to do a release later today.  Many thanks!

That also points out the need to use an architecture in our CI system that strictly requires aligned access.  I don't think that TravisCI or AppVeyor supports that currently.  Suggestions?

**Comment by FrancescAlted** [comment]
This fix is up.  @mwhudson I'd appreciate if you can test it in your machine.  Thanks in advance!

**Comment by mwhudson** [comment]
I tested the fix on the same porter box and the build now passes, so good job :)

**Comment by FrancescAlted** [comment]
For the record, a new 1.14.1 release with the fix is out.

**Comment by estan** [comment]
@FrancescAlted Excellent. @danstender kindly took the 1.14.2 release and made a new Debian package, and @ginggs made a feature freeze exception sync'ing the package to Ubuntu (ARM build succeeded this time), so things are moving along nicely.
